### PR TITLE
Add change history and update scudo cover

### PR DESCRIPTION
**Pull request by adityasaky**

### CODE REVIEW

**Review by jhdalek55 — APPROVED** [review]
LGM

**Review by jhdalek55 — CHANGES_REQUESTED** [review]
I think we want to leave in the original release date, and then on a separate line put the new date. If there are future changes, we could then replace the "updated" line.

**Review by jhdalek55 — APPROVED** [review]

**Comment by jhdalek55** [comment]
Should I merge?

**Comment by adityasaky** [comment]
Sure.

**Pull request merged**
