### PR TITLE
Add markdown file for first Uptane whitepaper

### PR DESCRIPTION
**Pull request by mnm678**

### CODE REVIEW

**Review by jhdalek55 — APPROVED** [review]
I'd like to begin work on this. I see no reason not to merge this commit.

**Comment by jhdalek55** [comment]
@mnm678  can I get write access to this repo? I'd like to start putting some text in place.

Thanks. Lois

**Comment by mnm678** [comment]
I don't have permission either. @trishankatdatadog can you add me and @jhdalek55 to this repo?

**Comment by jhdalek55** [comment]
Thanks, Marina.

**Comment by lukpueh** [comment]
@jhdalek55, I just sent you an invite for the "maintain" role, which includes write permissions to e.g. merge PRs or push directly to the repo.

**Comment by jhdalek55** [comment]
Thanks, Lukas

**Comment by jhdalek55** [comment]
@mnm678 I'm being given merge options here I don't understand. Can you help?

**Comment by lukpueh** [comment]
Do you mean these 3 options?

Screen Shot 2021-03-10 at 3 41 45 PM

I think either one is fine. But I generally prefer the default one -- "Create a merge commit" -- for two reasons:
1. It preserves the git history of your Pull Request as opposed to "Squash and merge", and
2. It leaves a record in the git history that your changes came from a Pull Request as opposed to "Rebase and merge"

**Comment by jhdalek55** [comment]
Thanks, @lukpueh. File has been merged. I am roughing out content offline right now and will commit some text here shortly.

**Pull request merged**
